"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import sys
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


env = environ.Env()
environ.Env.read_env(BASE_DIR / '.env')

AUTH_USER_MODEL = 'users.User'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SUPABASE_URL = env('SUPABASE_URL', default='')
DJANGO_SUPERUSER_EMAIL = env('DJANGO_SUPERUSER_EMAIL', default='')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=False)

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['127.0.0.1', 'localhost'])
RENDER_EXTERNAL_HOSTNAME = env('RENDER_EXTERNAL_HOSTNAME', default='')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # added apps
    'rest_framework',
    'corsheaders',
    'apps.articles',
    'apps.users',
    
    'apps.chatbot',
    'django_filters',
    'drf_spectacular',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

TEST_DATABASE_URL = env('TEST_DATABASE_URL', default='')
TESTING = 'test' in sys.argv
DATABASE_URL = env('DATABASE_URL', default='')
if TESTING and not TEST_DATABASE_URL:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': ':memory:',
        }
    }
elif TEST_DATABASE_URL:
    DATABASES = {
        'default': env.db('TEST_DATABASE_URL'),
    }
elif DATABASE_URL:
    DATABASES = {
        'default': env.db('DATABASE_URL'),
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': env('DB_NAME'),
            'USER': env('DB_USER'),
            'PASSWORD': env('DB_PASSWORD'),
            'HOST': env('DB_HOST'),
            'PORT': env('DB_PORT'),
        }
    }

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Admin-uploaded article images. These are deliberately NOT part of STATIC_ROOT:
# collectstatic/WhiteNoise never sees them, so /media/ is served by Django (see
# core/urls.py). `API_PUBLIC_BASE_URL` pins the public origin for deployments
# where the request host is not the address users browse to.
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'
API_PUBLIC_BASE_URL = env('API_PUBLIC_BASE_URL', default='')

STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage'},
}

# --- Article image storage -------------------------------------------------
#
# `USE_REMOTE_STORAGE` switches uploaded article images from the local filesystem
# to any S3-compatible object store. Supabase Storage is what this project uses;
# R2, Spaces and MinIO work unchanged by editing the endpoint.
#
# Local development and CI keep the filesystem so nothing here needs credentials
# to run the test suite.
#
# Two options below are easy to get wrong and fail *quietly*:
#
#   querystring_auth=False  Supabase object URLs are already public. Left True,
#                          django-storages appends a short-lived signature, so
#                          every stored image URL in article JSON expires.
#   custom_domain          Without it, generated URLs point at the S3 API
#                          endpoint, which requires a signature *even for a public
#                          bucket* — uploads succeed and every image 403s.
#                          The value is the public REST path and must omit the
#                          scheme, which django-storages adds itself.
#
# See `apps.articles.media.ImageUploadView` for the only caller.
USE_REMOTE_STORAGE = env.bool('USE_REMOTE_STORAGE', default=False)
SUPABASE_PROJECT_REF = env('SUPABASE_PROJECT_REF', default='')

# Placeholders copied from .env.example. These produce syntactically valid but
# entirely fictional hosts (`your-project-ref.storage.supabase.co`), so every
# uploaded image would 404 with no obvious cause — worth catching at startup.
_PLACEHOLDER_VALUES = {'', 'your-project-ref', 'your_project_ref', 'changeme', 'changeme'}

if USE_REMOTE_STORAGE:
    if SUPABASE_PROJECT_REF.strip().lower() in _PLACEHOLDER_VALUES:
        raise environ.ImproperlyConfigured(
            'SUPABASE_PROJECT_REF is still the placeholder value. Set it to your '
            "project ref — the subdomain of your project URL, e.g. 'abc123xyz' "
            'from https://abc123xyz.supabase.co — or set USE_REMOTE_STORAGE=False '
            'to use local filesystem storage.'
        )

    _bucket = env('SUPABASE_STORAGE_BUCKET', default='articles')
    for _name, _value in (
        ('SUPABASE_S3_ACCESS_KEY_ID', env('SUPABASE_S3_ACCESS_KEY_ID', default='')),
        ('SUPABASE_S3_SECRET_ACCESS_KEY', env('SUPABASE_S3_SECRET_ACCESS_KEY', default='')),
    ):
        if not _value or _value.lower() in _PLACEHOLDER_VALUES or _value.startswith('your-'):
            raise environ.ImproperlyConfigured(
                f'{_name} is missing or still a placeholder. Generate a pair in '
                'the Supabase dashboard under Storage -> S3 Settings. These are '
                'S3 protocol keys, NOT the service_role key.'
            )
    STORAGES['default'] = {
        'BACKEND': 'storages.backends.s3.S3Storage',
        'OPTIONS': {
            'bucket_name': _bucket,
            # The dedicated storage hostname, not the project hostname.
            'endpoint_url': env(
                'SUPABASE_S3_ENDPOINT_URL',
                default=(
                    f'https://{SUPABASE_PROJECT_REF}.storage.supabase.co/storage/v1/s3'
                ),
            ),
            'access_key': env('SUPABASE_S3_ACCESS_KEY_ID', default=''),
            'secret_key': env('SUPABASE_S3_SECRET_ACCESS_KEY', default=''),
            'region_name': env('SUPABASE_S3_REGION', default=SUPABASE_PROJECT_REF),
            # Supabase does not support virtual-hosted-style URLs.
            'addressing_style': 'path',
            'signature_version': 's3v4',
            'querystring_auth': False,
            'custom_domain': (
                f'{SUPABASE_PROJECT_REF}.supabase.co/storage/v1/object/public/{_bucket}'
            ),
            # Images are public article assets; never make them private.
            'default_acl': None,
        },
    }

# --- Image optimisation ----------------------------------------------------
#
# Uploaded images are downscaled and re-encoded before storage. The reading
# column is ~800px wide, so the default caps the long edge at 2x that.
# See apps.articles.image_processing.
IMAGE_MAX_DIMENSION = env.int('IMAGE_MAX_DIMENSION', default=1600)
IMAGE_WEBP_QUALITY = env.int('IMAGE_WEBP_QUALITY', default=82)
IMAGE_WEBP_METHOD = env.int('IMAGE_WEBP_METHOD', default=6)
IMAGE_MIN_SAVINGS_RATIO = env.float('IMAGE_MIN_SAVINGS_RATIO', default=0.10)

CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in env.list('CORS_ALLOWED_ORIGINS', default=['http://localhost:3000'])
    if origin.strip()
]

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in env.list('CSRF_TRUSTED_ORIGINS', default=['http://localhost:3000'])
    if origin.strip()
]

CORS_ALLOW_ALL_ORIGINS = DEBUG

if not DEBUG:
    # Render terminates SSL at the proxy/load balancer.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = env.bool('SECURE_SSL_REDIRECT', default=False)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'apps.users.authentication.SupabaseJWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_PAGINATION_CLASS':
        'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,

    'DEFAULT_FILTER_BACKENDS': [
    'django_filters.rest_framework.DjangoFilterBackend',
    'rest_framework.filters.SearchFilter',
    'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'CSEHub API',
    'DESCRIPTION': 'Auto-generated API documentation for CSEHub.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

# RAG is an optional integration at Django startup.  Its commands and chat
# endpoint provide a controlled error when these are not configured.
PINECONE_API_KEY = env('PINECONE_API_KEY', default='')
PINECONE_INDEX_NAME = env('PINECONE_INDEX_NAME', default='')
GEMINI_API_KEY = env('GEMINI_API_KEY', default='')
GEMINI_MODEL = env('GEMINI_MODEL', default='gemini-2.5-flash-lite')
