# Generated by Django 6.0.3 on 2026-10-06 18:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_editorjs_article_metadata"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["-is_published", "-created_at"],
                name="articles_ar_is_publ_f56358_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["is_featured"], name="articles_ar_is_feat_d43b7b_idx"
            ),
        ),
    ]
